name: Branch

on:
  push:
    branches-ignore:
      - master

jobs:
  Cancel-Old-Runs:
    runs-on: ubuntu-latest

    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  Test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run bot
